name: thryfted_flutter
description: "Thryfted marketplace mobile app built with Flutter - A sustainable fashion resale platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.4.1
  
  # Navigation
  go_router: ^14.6.2
  
  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Storage & Persistence
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # Forms & Validation
  reactive_forms: ^17.0.1
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.4
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  
  # Device & Platform
  device_info_plus: ^10.1.2
  package_info_plus: ^8.1.0
  connectivity_plus: ^6.1.0
  
  # Utilities
  intl: ^0.20.2
  logger: ^2.4.0
  uuid: ^4.5.1
  
  # Maps & Location
  geolocator: ^13.0.2
  
  # Social & Sharing
  share_plus: ^10.1.2
  
  # Biometrics
  local_auth: ^2.3.0
  
  # Clerk Authentication
  clerk_flutter: ^0.0.10-beta
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # Enable generation of localization
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
